---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-helm-operator-ketches-cn-v1alpha1-helmrelease
  failurePolicy: Fail
  name: vhelmrelease.kb.io
  rules:
  - apiGroups:
    - helm-operator.ketches.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - helmreleases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-helm-operator-ketches-cn-v1alpha1-helmrepository
  failurePolicy: Fail
  name: vhelmrepository.kb.io
  rules:
  - apiGroups:
    - helm-operator.ketches.cn
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - helmrepositories
  sideEffects: None
